//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CTSize
    {
        [DisplayName("Size")]
        public int MaSize { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> Sluong { get; set; }
        [DisplayName("Sản phẩm")]
        public int MaSP { get; set; }
    
        public virtual SIZE SIZE { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
