//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
        [DisplayName("Đơn hàng")]
        public int MaDH { get; set; }
        [DisplayName("Ngày đặt")]
        public Nullable<System.DateTime> NgayDat { get; set; }
        [DisplayName("Tên khách hàng")]
        public Nullable<int> UserID { get; set; }
        [DisplayName("Ngày giao")]
        public Nullable<System.DateTime> NgayGiao { get; set; }
        [DisplayName("Thanh toán")]
        public Nullable<bool> DaThanhToan { get; set; }
        [DisplayName("Tình trạng ĐH")]
        public Nullable<int> TinhTrang { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<double> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
    }
}
