//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
        [DisplayName("Mã khuyến mãi")]
        public int MaKM { get; set; }
        [DisplayName("Nội dung")]
        public string Mota { get; set; }
        [DisplayName("Giá trị KM")]
        public Nullable<double> GiaTriKM { get; set; }
        [DisplayName("Ngày bắt đầu")]
        public Nullable<System.DateTime> NgayBD { get; set; }
        [DisplayName("Ngày kết thúc")]
        public Nullable<System.DateTime> NgayKT { get; set; }
        [DisplayName("Khuyến mãi")]
        public string TenKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
