//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class RATING
    {
        public int id { get; set; }
        [DisplayName("Sản phẩm")]
        public Nullable<int> masp { get; set; }
        [DisplayName("Đánh giá")]
        public Nullable<int> rate { get; set; }
        [DisplayName("Ngày đánh giá")]
        public Nullable<System.DateTime> crdate { get; set; }
        [DisplayName("Nội dung")]
        public string noidung { get; set; }
        [DisplayName("Tên khách hàng")]
        public string hoten { get; set; }
        [DisplayName("Tên khách hàng")]
        public Nullable<int> iduser { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
