//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string MaTT { get; set; }
        public int MaDH { get; set; }
        public System.DateTime NgayTra { get; set; }
        public double TienTra { get; set; }
        public int MaPT { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual PHUONGTHUCTT PHUONGTHUCTT { get; set; }
    }
}
